
export const FETCH_MERCHANTS_BEGIN   = 'FETCH_MERCHANTS_BEGIN';
export const FETCH_MERCHANTS_SUCCESS = 'FETCH_MERCHANTS_SUCCESS';
export const FETCH_MERCHANTS_FAILURE = 'FETCH_MERCHANTS_FAILURE';

export const ADD_NEW_MERCHANT = 'ADD_NEW_MERCHANT';
export const EDIT_MERCHANT = 'EDIT_MERCHANT';
export const DELETE_MERCHANT = 'DELETE_MERCHANT';